const URL = process.env.REACT_APP_API_URL;

export const urls = {
    LOGIN_URL: `/jwt/login`,
    GET_ALL_PAY_SYS_TERMINALS_URL: `/api/get_all_pay_sys_terminals`,
    GET_ALL_MCC_URL: `/api/get_all_mcc`,
    GET_ALL_MCC_Page_URL: `/api/get_all_mcc_page`,
    GET_ALL_CITIES_URL: `/api/get_all_cities`,
    GET_ALL_CITIES_PAGE_URL: `/api/get_all_cities_page`,
    GET_ALL_POS_MODELS_URL: `api/get_all_pos_models`,
    GET_ALL_PAY_SYS_URL: `api/get_all_pay_sys`,

    GET_TOKEN_URL: "",
    GET_USER_INFO_URL: "https://fakestoreapi.com/users/1",
    GET_USERS_URL: "",
    GET_TERMINALS_BY_PAGE_URL: "",
    GET_TRANSACTIONS_BY_PAGE_URL: "",
    GET_TERMINALS_TYPES_URL: "",
    GET_TERMINALS_REPORT: "",
    GET_TRANSACTIONS_REPORT: "",
    GET_BANKS_URL: "",
    GET_PAYMENT_SYSTEMS_URL: "",
    GET_TRANSACTION_TYPES_URL: "",
    GET_LANGUAGES_URL: "",
    GET_ROLES_URL: "",
    POST_NEW_TERMINAL_URL: "",
    POST_NEW_USER_URL: "",
    POST_NEW_BANK_URL: "",
    POST_FORGOT_PASSWORD_URL: "",
    PUT_TERMINAL_DATA_URL: "",
    PUT_USER_DATA_URL: "",
    PUT_BANK_DATA_URL: "",
    PUT_CHANGE_PASSWORD_URL: "",
    DELETE_TERMINAL_DATA_URL: "",
    DELETE_USER_DATA_URL: "",
    DELETE_BANK_DATA_URL: "",
};